// Disposable / throwaway email-domain blocklist.
// Curated subset of the most common providers; extend as needed.
// Matches case-insensitively against the part after the '@'.

const DISPOSABLE_DOMAINS = new Set<string>([
  '0-mail.com',
  '10minutemail.com',
  '20minutemail.com',
  'anonbox.net',
  'binkmail.com',
  'bouncr.com',
  'burnermail.io',
  'deadaddress.com',
  'discard.email',
  'dispostable.com',
  'emailondeck.com',
  'fakeinbox.com',
  'fake-mail.net',
  'fakemail.net',
  'getairmail.com',
  'getnada.com',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'harakirimail.com',
  'inboxbear.com',
  'inboxkitten.com',
  'jetable.org',
  'kasmail.com',
  'mailcatch.com',
  'maildrop.cc',
  'mailinator.com',
  'mailinator.net',
  'mailnesia.com',
  'mintemail.com',
  'mohmal.com',
  'moakt.com',
  'mvrht.com',
  'mytrashmail.com',
  'nada.email',
  'nowmymail.com',
  'opayq.com',
  'pokemail.net',
  'rcpt.at',
  'sharklasers.com',
  'shrtco.de',
  'sneakemail.com',
  'spam4.me',
  'spamavert.com',
  'spamex.com',
  'spamgourmet.com',
  'spamhole.com',
  'sogetthis.com',
  'tempinbox.com',
  'tempmail.com',
  'temp-mail.org',
  'tempmailaddress.com',
  'tempmailo.com',
  'temporarymail.com',
  'throwawaymail.com',
  'trashmail.com',
  'trashmail.io',
  'trashmail.me',
  'trbvm.com',
  'wegwerfemail.de',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'zetmail.com',
]);

export function isDisposableEmailDomain(email: string): boolean {
  const at = email.lastIndexOf('@');
  if (at < 0) return false;
  const domain = email.slice(at + 1).trim().toLowerCase();
  return DISPOSABLE_DOMAINS.has(domain);
}
